
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Feb 10 00:30:06 CET 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EQUALSTO = 30;
  public static final int LBRACKET = 16;
  public static final int CONST = 15;
  public static final int CONTINUE = 44;
  public static final int LPAREN = 6;
  public static final int GREATER = 32;
  public static final int SEMI = 5;
  public static final int MINUS = 36;
  public static final int LESS = 34;
  public static final int GREQ = 33;
  public static final int CHARACTER = 11;
  public static final int RPAREN = 7;
  public static final int AND = 20;
  public static final int RECORD = 18;
  public static final int OR = 19;
  public static final int BOOL = 25;
  public static final int COMMA = 12;
  public static final int INC = 21;
  public static final int DIV = 38;
  public static final int PLUS = 10;
  public static final int LESSEQ = 35;
  public static final int IF = 27;
  public static final int DOT = 23;
  public static final int EOF = 0;
  public static final int RETURN = 9;
  public static final int RBRACKET = 17;
  public static final int EQUAL = 8;
  public static final int NEW = 47;
  public static final int error = 1;
  public static final int MUL = 37;
  public static final int MOD = 39;
  public static final int NUMBER = 24;
  public static final int BREAK = 43;
  public static final int IDENT = 26;
  public static final int VOID = 14;
  public static final int COLON = 40;
  public static final int LBRACE = 3;
  public static final int ELSE = 28;
  public static final int READ = 45;
  public static final int ENUM = 29;
  public static final int GOTO = 46;
  public static final int WHILE = 42;
  public static final int RBRACE = 4;
  public static final int PROG = 2;
  public static final int DEC = 22;
  public static final int DO = 41;
  public static final int PRINT = 13;
  public static final int NOTEQ = 31;
}

